# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce59bac339bd73b5de0a02cf0326dff44b818118ecf08ee060c31d63655f3771ac6dbd7ec85eb9805a1806aec3758dfac632929bb0079b3e343ab980d1186da7

test:
  secret_key_base: 0c75233100da2d5efd6c59af51ddf2211e9241ed0d47774990efc120cb4da96436094c3d84067c610090c2b889d36fa4777bfa1182b7ef43f5707ac3abba2f7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
